services:
  leasedkeyq-vscode:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CREATE_VSCODE_USER: "true"
    volumes:
      - .:/workspace:cached
    environment:
      - HOST_USER=${USER}
    user: vscode
    command: sleep infinity
